name: Daily Activity Generator

on:
  schedule:
    # Runs every day at 3 different times (UTC)
    - cron: "0 6 * * *"  # 6:00 UTC
    - cron: "0 12 * * *" # 12:00 UTC
    - cron: "0 18 * * *" # 18:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-activity:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Generate commits
        run: python generate_activity.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push
